ConceptMan/urls.py
from django.urls import re_path as url
from django_keycloak.decorators import group_required, check_keycloak_status
from website.security.url_decorators_for_database_content import *
from .Views.views import *
from .Views import *
from .Views.modal import *

app_name = "ConceptMan"
group_name = "/be_paramount/app-conceptman"

_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None, fi=None: _auth(project_security_check(f, app_name=a, model_name=m, field=fi))
_object = lambda f, a=None, m=None, fi=None: _auth(object_security_check(f, app_name=a, model_name=m, field=fi))
_owner = lambda f, a=None, m=None, fi=None: _auth(owner_security_check(f, app_name=a, model_name=m, field=fi))




urlpatterns = [

    #part
    url(r'^part/create/$', _auth(part_create), name='part_create'),
    url(r'^part/(?P<pk>[0-9]+)/update/$', _auth(part_update), name='part_update'),
    url(r'^part/(?P<pk>[0-9]+)/delete/$', _auth(part_delete), name='part_delete'),

    #concept
    url(r'^concept/create/$', _auth(concept_create), name='concept_create'),
    url(r'^concept/(?P<pk>[0-9]+)/update/$', _auth(concept_update), name='concept_update'),
    url(r'^concept/(?P<pk>[0-9]+)/delete/$', _auth(concept_delete), name='concept_delete'),

    url(r'vehicles/$', _auth(index_vehicle.as_view()), name ='index_vehicle'),
    url(r'vehicle/(?P<pk>[0-9]+)/concepts/$', _auth(index_concept.as_view()), name ='index_concept'),

    #/conceptdetail/  
    url(r'conceptdetail/(?P<pk>[0-9]+)/partindex/$', _auth(ConceptDetailView_Part.as_view()), name ='conceptdetail_part'),   
    url(r'conceptdetail/(?P<pk>[0-9]+)/materialindex/$', _auth(ConceptDetailView_Engineering_Material.as_view()), name ='conceptdetail_engineering_material'),     
    url(r'conceptdetail/(?P<pk>[0-9]+)/boltcaseindex/$', _auth(ConceptDetailView_Bolt_Case.as_view()), name ='conceptdetail_bolt_case'),     

    url(r'^parts/(?P<pk>[0-9]+)/detail/$', _auth(PartDetailView.as_view()), name ='part_detailview'),
    url(r'^parts/(?P<pk>[0-9]+)/detail/select/manufacturingprocess/$', _auth(part_manufacturingprocess), name ='part_select_manufacturingprocess'),

]                                

EcoMan/urls.py
from django.urls import *
from django.urls import re_path as url
from django_keycloak.decorators import group_required_account_not_expired, check_keycloak_status, group_required
from website.security.url_decorators_for_database_content import *
from .Views import *
app_name = "EcoMan"
group_name ="/be_paramount/app-ecoman"
_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None, fi=None: _auth(project_security_check(f, app_name=a, model_name=m, field=fi))
_object = lambda f, a=None, m=None, fi=None: _auth(object_security_check(f, app_name=a, model_name=m, field=fi))
_owner = lambda f, a=None, m=None, fi=None: _auth(owner_security_check(f, app_name=a, model_name=m, field=fi))

urlpatterns = [


    url(r'index/$', _auth(index.as_view()), name ='index'),

    url(r'analysis_playground/welcome_screen/$', _auth(qlca_welcome_screen.as_view()), name ='qlca_welcome_screen'),
    url(r'analysis/welcome_screen$', _auth(qlca_analysis_welcome_screen.as_view()), name ='qlca_analysis_welcome_screen'),
    #lca part
    #url(r'^lcapart/create/$', _auth(lca_part_create_modal), name='lca_part_create_modal'),
    url(r'^lcapart/create/pk_analysis:(?P<pk_analysis>[0-9]*)/is_automotive:(?P<is_automotive>True|False)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_create_modal), name='lca_part_create_modal'),
    url(r'^lcapart/(?P<pk>[0-9]+)/update/is_automotive:(?P<is_automotive>True|False)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_update), name='lca_part_update'),
    url(r'^lcapart/(?P<pk>[0-9]+)/delete/$', _auth(lca_part_delete, required_roles = ['edag_worker'],), name='lca_part_delete'),

    #lca parts operations playground
    url(r'^lca_part_switch_analysis/source_analysis/(?P<pk_source_analysis>[0-9]+)/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_move), name='lca_part_move'),
    url(r'^lca_part_add_mirror/source_analysis/(?P<pk_source_analysis>[0-9]+)/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_add_mirror), name='lca_part_add_mirror'),
    url(r'^lca_part_remove_mirror/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_remove_mirror), name='lca_part_remove_mirror'),
    url(r'^(?P<pk_analysis>[0-9]+)/clone_lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(quick_part_clone), name='quick_part_clone'),


    #analysis_comparison_playgroud
    url(r'^analysis_comparison/(?P<pk>[0-9]+)/playgrounddetail/$', _auth(analysis_comparison_detail_view.as_view()), name ='analysis_comparison_detail_view'),
    url(r'^current/playgrounddetail/$', _auth(continue_analysis_comparison_detail_view), name ='continue_analysis_comparison_detail_view'),
    url(r'index/qlcaplayground/$', _auth(analysis_comparison_index_view.as_view()), name ='analysis_comparison_index_view'),
    #analysis_comparison #modal windows
    url(r'^analysis_playground/createandedit/$', _auth(analysis_comparison_create_and_edit), name='analysis_comparison_create_and_edit'),
    url(r'^analysis_playground/create/$', _auth(analysis_comparison_create), name='analysis_comparison_create'),
    url(r'^analysis_playground/(?P<pk>[0-9]+)/update/$', _auth(analysis_comparison_update), name='analysis_comparison_update'),
    url(r'^analysis_playground/(?P<pk>[0-9]+)/update_report_settings/$', _auth(analysis_comparison_report_update), name='analysis_comparison_report_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', _auth(analysis_comparison_delete, required_roles = ['edag_worker'],), name='analysis_comparison_delete'),

    # analysis
    url(r'index/analysis/$', _auth(analysis_index_view.as_view()), name='analysis_index_view'),
    url(r'^analysis/current/detail/$', _auth(continue_analysis_detail_view), name ='continue_analysis_detail_view'),

    url(r'^analysis/(?P<pk>[0-9]+)/playgroundonecolumn/$', _owner(analysis_detail_view.as_view(), a='EcoMan', m='Analysis'), name='analysis_detail_view'),

    #analysis #modal windows   
    url(r'^analysis/createandedit/$', _auth(analysis_create_and_edit), name='analysis_create_and_edit'),
    url(r'^analysis/(?P<pk>[0-9]+)/update/$', _auth(analysis_update), name='analysis_update'),
    url(r'^analysis/(?P<pk>[0-9]+)/delete/$', _auth(analysis_delete, required_roles = ['edag_worker'],), name='analysis_delete'),
    url(r'^analysis/(?P<pk>[0-9]+)/update_report_settings/$', _auth(analysis_settings_update), name='analysis_settings_update'),

    #analysis_comparison
    url(r'index/qlcacompare/$', _auth(analysis_index_view_compare.as_view()), name ='qlca_compare'),
    url(r'index/qlcacompare/create$', _auth(analysis_comparison_create_compare), name ='analysis_comparison_create_compare'),

    #support ticket
    url(r'^supportticket/create/$', _auth(lca_support_ticket_create_modal, required_roles = ['edag_worker'],), name='lca_support_ticket_create_modal'),

    #print playground report
    url(r'^(?P<pk>[0-9]+)/print/$', _auth(lca_comparison_print_reportlab), name='lca_comparison_print_reportlab'),
    
    #print playground report
    url(r'^analysis/(?P<pk>[0-9]+)/print/$', _auth(lca_analysis_print_reportlab), name='lca_analysis_print_reportlab'),

    #LCA Part lca_part_add_process
    url(r'^lca_part/(?P<pk_lca_part>[0-9]*)/addnewlcaprocess/lca_step/(?P<lca_step>[\w\-]+)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_add_process_instance), name='lca_part_add_process_instance'),

    url(r'^lca_part/(?P<pk>[0-9]*)/addnew:process_circularity/$', _auth(step1upstream_add_process_circularity), name='step1upstream_add_process_circularity'),
    url(r'^lca_part/(?P<pk>[0-9]*)/addnew:transport_circularity/$', _auth(step1upstream_add_transport_circularity), name='step1upstream_add_transport_circularity'),
    url(r'^lca_part/(?P<pk_lca_part>[0-9]*)/toggle_ispartreused/$', _auth(lcastep_ispartreused_status), name='lcastep_ispartreused_status'),

    #analysis modal
    url(r'^analysis_comparison/(?P<pk>[0-9]*)/addnew:utilisation/$', _auth(analysis_comparison_add_utilisation), name='analysis_comparison_add_utilisation'),
    url(r'^analysis/(?P<pk>[0-9]*)/addnew:utilisation/$', _auth(analysis_add_utilisation), name='analysis_add_utilisation'),
    #instance process
    url(r'^material_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)$', _auth(material_process_instance_update), name='material_process_instance_update'),
    url(r'^processing_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)/update/$', _auth(processing_process_instance_update), name='processing_process_instance_update'),
    url(r'^transport_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)$', _auth(transport_process_instance_update), name='transport_process_instance_update'),
    url(r'^instance_lca_process/(?P<pk>[0-9]+)/delete/$', _auth(instance_idemat_process_delete), name='instance_idemat_process_delete'),
    url(r'^lca_part/(?P<pk_process_instance>[0-9]*)/process_instance_is_active/$', _auth(process_instance_is_active), name='process_instance_is_active'),

    #instance_utilisation_process   (word instance should be removed - it is not the same as with idemate process and instance idemat process)

    url(r'^utilisation_process/create/analysis:(?P<pk_analysis>[0-9]*)$', _auth(utilisation_instance_process_create), name='utilisation_instance_process_create'),
    url(r'^utilisation_process/create/$', _auth(utilisation_instance_process_create), name='utilisation_instance_process_create'),
    url(r'^utilisation_process/(?P<pk>[0-9]+)/delete/$', _auth(utilisation_instance_process_delete), name='utilisation_instance_process_delete'),
    url(r'^utilistaion_process/(?P<pk_instance>[0-9]*)/update/$', _auth(utilisation_instance_process_update), name='utilisation_instance_process_update'),

    #instance_circularity_process
    url(r'^circularity_process/(?P<pk_circularity_process>[0-9]*)/update/$', _auth(circularity_process_update), name='circularity_process_update'),

    #LCA Database
    url(r'^lca_db/(?P<pk>[0-9]+)/processlist/$', _auth(LcaProcessListView.as_view()), name='lca_process_list'),
    
    url(r'^lca_db/open/list/$', _auth(open_database_index_view.as_view()), name='open_database_index_view'),
    url(r'^lca_db/organisation/list/$', _auth(edag_database_index_view.as_view()), name='edag_database_index_view'),
    url(r'^lca_db/project/list/$', _auth(project_database_index_view.as_view()), name='project_database_index_view'),
    
    url(r'^lca_db/create/$', _auth(lca_db_create), name='lca_db_create'),
    url(r'^lca_db/(?P<pk>[0-9]+)/update/$', _auth(lca_db_update), name='lca_db_update'),
    url(r'^lca_db/(?P<pk>[0-9]+)/importexcel/$', _auth(lca_db_import_excel, required_roles = ['edag_worker']), name='lca_db_import_excel'),
    url(r'^lca_db/(?P<pk>[0-9]+)/exportexcel/$', _auth(lca_db_export_excel, required_roles = ['edag_worker']), name='lca_db_export_excel'),

    url(r'^lca_db/(?P<pk>[0-9]+)/delete/$', _auth(lca_db_delete, required_roles = ['edag_worker'], required_groups=[group_name + 'user-professional']), name='lca_db_delete'),
    url(r'^lca_db/(?P<pk>[0-9]+)/restore/$', _auth(lca_db_restore, required_roles = ['edag_worker'], required_groups=[group_name + 'user-professional']), name='lca_db_restore'),
    url(r'^lca_db/create/excel_import$', _auth(lca_db_create, required_roles = ['edag_worker']), name='lca_db_create'),
    url(r'^lca_db/download_lca_template/$', _auth(lca_database_template_download), name='lca_database_template_download'),

    #lca_process

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django_keycloak.decorators import group_required, check_keycloak_status
from django_keycloak.keycloak_manager import keycloak_manager
from django.urls import path, include
from django.urls import re_path as url
from django.views.generic import TemplateView
from website.views import *
from website.views.modal import *
from CatiaFramework.urls.urls_main import urls_modal

from website.security.url_decorators_for_database_content import *

admin.site.site_header = 'BE PARAMOUNT admin page'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'HTML title from adminsitration' # default: "Django site admin"


# group_name_professional ="/be_paramount/user-professional"
group_name ="/be_paramount"
app_name = 'website'
_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None: _auth(project_security_check(f, app_name=a, model_name=m))
_object = lambda f, a=None, m=None: _auth(object_security_check(f, app_name=a, model_name=m))
_owner = lambda f, a=None, m=None: _auth(owner_security_check(f, app_name=a, model_name=m))





'''
LOAD appurlspatterns based on configured system (env file)
'''

app_url_patterns = list()

for app in settings.GROUPS.values():
    match app:
        case 'boltman':
            app_url_patterns.append(path('bolt/', include('BoltMan.urls')))
        case 'matman':
            app_url_patterns.append(path('material/', include('MatMan.urls')))
        case 'conceptman':
            app_url_patterns.append(path('concept/', include('ConceptMan.urls')))            
        case 'ecoman':
            app_url_patterns.append(path('qlca/', include('EcoMan.urls')))
        case 'catfrm':
            app_url_patterns.append(path('catiaframework/', include('CatiaFramework.urls')),)
        case 'normman':
            app_url_patterns.append(path('shared_components/', include('NormMan.urls')))


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_home, name='redirect_to_home'),
    url(r'home/$', _auth(index.as_view()), name ='home'),
    url(r'err/not_in_group$', TemplateView.as_view(template_name='website/not_in_group_err.html'), name ='not_in_group'),
    url(r'err/account_expired$', TemplateView.as_view(template_name='website/account_expired_err.html'), name ='account_expired'),

    # Application views
    # ToDo: Separate for future

    # Project
    url(r'^project/create/$', _auth(project_create, required_roles=["edag_worker"], ), name='project_create'),
    url(r'^project/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_update), name='project_update'),
    url(r'^project/(?P<uuid>[0-9a-t\-]{32,})/delete/$', _auth(project_delete), name='project_delete'),
    # Vehicle
    url(r'^vehicles/create/$', _auth(vehicle_create), name='vehicle_create'),
    url(r'^vehicles/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(vehicle_update), name='vehicle_update'),
    url(r'^vehicles/(?P<uuid>[0-9a-t\-]{32,})/delete/$', _auth(vehicle_delete), name='vehicle_delete'),
    # Production rate
    url(r'^production_rate/(?P<pk>[0-9]+)/update/$', _auth(production_rate_update), name='production_rate_update'),
    # Userproject
    url(r'^project_user_update/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_user_update), name='project_user_update'),
    url(r'^project_user_select_current_project/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_user_select_current_project, required_roles=["edag_worker"]), name='project_user_select_current_project'),
    url(r'^project_update_authorised_users/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_update_authorised_users, required_roles=["edag_worker"]), name='project_update_authorised_users'),
    # Info modal
    url(r'^info/concept/$', _auth(info_concept), name='info_concept'),
    url(r'load-project-users/$', _auth(load_project_users), name='load_project_users'),
    
    #Token
    url(r'^tokens/create/component_uuid:(?P<uuid_component>[0-9a-t\-]{32,})$', _auth(token_create_modal), name='token_create_modal'),


    # Websocket
    path('rooms/', index_view, name='chat-index'),
    path('rooms/<str:room_name>/', room_view, name='chat-room'),
    # Keycloak redirect from all application endpoints
    path('user/login/', lambda request: redirect(f"{request.scheme}://{request.headers['Host']}/keycloak/login"), name='login_redirect'),
    path('keycloak/login/', keycloak_manager.keycloak_admin_redirect, name='keycloak_admin_redirect'),
    # Keycloak login
    path('home/keycloak/expired_login/', keycloak_manager.expired_login, name='expired_login'),    
    path('keycloak/login/callback/', keycloak_manager.keycloak_login, name='keycloak_login'),
    path('keycloak/logout/', keycloak_manager.keycloak_logout, name='keycloak_logout'),    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + app_url_patterns

website/views/rooms.py
from django.shortcuts import render

from website.models import Room


def index_view(request):
    return render(request, 'website/chat/index.html', {
        'rooms': Room.objects.all(),
    })


def room_view(request, room_name):
    chat_room, created = Room.objects.get_or_create(name=room_name)
    return render(request, 'website/chat/room.html', {
        'room': chat_room,
    })

website/templates/website/current_analysis.html
{% load static %}


<div class="card  mx-1 my-3 w-100">
    <div class="card-body">
        <strong> #Current Analysis </strong>
        {% if current_analysis.logo %}
            <img class="card-img-top" src="{{ current_analysis.logo.url }}" alt="Analysis image not available">
        {% else %}
            <img class="card-img-top" src="{% static '/EcoMan/images/QLCA_Icon.png' %}" alt="Vehicle image not available1">
        {% endif %}
    </div>
    <div class="card-footer">

        {% if current_analysis %}
        <strong>Name:</strong> {{ current_analysis.name }}<br>
        <strong>Project:</strong> {{ current_analysis.project_model.reference_project.name }}<br>
        <strong>Owner:</strong> {{ current_analysis.owner }}<br>
        <strong>Is Public:</strong> {{ current_analysis.analysis_settings.is_public }}<br>

        {% endif %}

    </div>
    <div class="container-fluid" id="objects-container">
        <div class="row">

            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window-xl" data-url="{% url 'EcoMan:analysis_update' current_analysis_id %}">
                Edit
            </button>
            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window" data-url="{% url 'EcoMan:analysis_settings_update' current_analysis_id %}">
                Report options
            </button>
            <a type="button" class="btn btn-warning btn-sm btn-block"  href="{% url 'EcoMan:lca_analysis_print_reportlab' pk=current_analysis_id %}"
                onclick="return confirm('Do you really want to generate pdf document?');">
                <i class="fas fa-print-alt"></i> Print Report
            </a>

            <a  type="button" class="btn btn-warning btn-sm btn-block" href="{% url 'EcoMan:analysis_to_json' pk_analysis=analysis.id %}" >
                Export JSON File </a>
            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window-xl" data-url="{% url 'EcoMan:json_import_analysis_append' pk_analysis=analysis.id %}">
                Import JSON File
            </button>
        </div>
    </div>
</div>

website/templates/website/current_lca_database.html
{% load static %}


<div class="card  mx-1 my-3 w-100">
    <div class="card-body">
        <strong> #Current LCA Database </strong>

        {% if database.logo %}
            <img class="card-img-top" src="{{ database.logo.url }}" alt="Database image not available" > 
        {% else %}
            <img class="card-img-top" src="{% static 'EcoMan/images/LCA_Database_Idemat.png' %}" alt="Database image not available">
        {% endif %}

    </div>
    <div class="card-footer">

        {% if database %}
        <strong>ID:</strong> <br>{{ database.id }}<br>
        <strong>Name:</strong> <br>{{ database.name }}<br>
        <strong>Owner:</strong> <br>{{ database.owner }}<br>
        <strong>Accessibility:</strong> <br>{{ database.accessibility}}<br>
        <strong>Info:</strong> <br>{{ database.note }}<br>
        {% endif %}

    </div>
   <div class="container-fluid" id="objects-container">
        <div class="row">

        {% if is_staff == True %}

            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window" data-url="{% url 'EcoMan:lca_db_update' database.id %}" >
                        Edit Header Data
            </button>
            {% if is_add_new_process_allowed == True %}
            <button type="button" class="btn btn-warning btn-sm btn-block js-object-create" id="#modal-window-xl" data-url="{% url 'EcoMan:lca_process_create' database.id %}" >
                        Add New Process
            {% else %}
            <button type="button" class="btn btn-warning btn-sm btn-block disabled" disabled>
                Add New Process
            {% endif %}
            </button>
            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window" data-url="{% url 'EcoMan:lca_db_import_excel' database.id %}" disabled>
                        Append Processes from Template
            </button>
            <a href="{% url 'EcoMan:lca_db_export_excel' database.id %}" class="btn btn-warning btn-sm btn-block" role="button" aria-disabled="true">Export Processes to Excel</a>
            
        {% endif %}
        {% if database.accessibility == 'OPEN'%}
            <a href="{% url 'EcoMan:lca_db_export_excel' database.id %}" class="btn btn-warning btn-sm btn-block" role="button" aria-disabled="true">Export Processes to Excel</a>
        {% endif %}
        </div>
    </div>
</div>

website/templates/website/current_material.html
{% load static %}


<div class="card  mx-1 my-3 w-100">
    <div class="card-body">

        <img class="card-img-top" src="{% static '/website/images/Material_Icon.png' %}" alt="Material image not available1">

    </div>
    <div class="card-footer">
        <h5 class="card-title">{{ material.name }}</h5>
    </div>
    <div class="container-fluid" id="materials-container">
        <div class="row">

                <button type="button" class="btn btn-warning btn-sm btn-block js-vehicle-update " data-url=#> {#"{% url 'MatMan:material_delete' material.id %}">#}
                    Edit
                </button>

                <button type="button" class="btn btn-danger btn-sm btn-block js-vehicle-delete " data-url=#> {#"{% url 'MatMan:material_delete' material.id %}">#}
                    Delete
                </button>

        </div>
    </div>
</div>

website/templates/website/current_part.html
{% load static %}


<div class="card  mx-1 my-3 w-100">
    <div class="card-body">
        {% if object.logo == 'Default Part Logo' %}
        <img class="card-img-top" src="{% static '/website/images/Part_Icon.png' %}" alt="Part image not available1">
        {% else %}
        <img class="card-img-top" src="{{ object.logo }}" alt="Part image not available">
        {% endif %}
    </div>
    <div class="card-footer">
        <h5 class="card-title">{{ object.name }}</h5>
    </div>
    <div class="container-fluid" id="parts-container">
        <div class="row">

                <button type="button" class="btn btn-warning btn-sm btn-block js-part-update " data-url="{% url 'ConceptMan:part_update' object.id %}">
                    Edit
                </button>

                <button type="button" class="btn btn-danger btn-sm btn-block js-part-delete " data-url="{% url 'ConceptMan:part_delete' object.id %}">
                    Delete
                </button>

        </div>
    </div>
</div>

website/templates/website/current_playground.html
{% load static %}


<div class="card  mx-1 my-3 w-100">
    <div class="card-body">
        <strong> #Current Analysis </strong>
        {% if current_analysis.logo %}
            <img class="card-img-top" src="{{ current_analysis.logo.url }}" alt="Analysis image not available">
        {% else %}
            <img class="card-img-top" src="{% static '/website/images/Playground_Icon.png' %}" alt="Vehicle image not available1">
        {% endif %}
    </div>
    <div class="card-footer">

        {% if current_analysis %}
        <strong>Name:</strong> {{ current_analysis.name }}<br>
        <strong>Owner:</strong> {{ current_analysis.owner }}<br>
        <strong>Is Public:</strong> {{ current_analysis.analysis_settings.is_public }}<br>
        {% endif %}

    </div>
    <div class="container-fluid" id="objects-container">
        <div class="row">

            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window-xl" data-url="{% url 'EcoMan:analysis_comparison_update' current_analysis_comparison_id %}">
                Edit
            </button>
            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window" data-url="{% url 'EcoMan:analysis_comparison_report_update' current_analysis_comparison_id %}">
                Report options
            </button>
            <a type="button" class="btn btn-warning btn-sm btn-block"  href="{% url 'EcoMan:lca_comparison_print_reportlab' pk=current_analysis_comparison_id %}"
                onclick="return confirm('Do you really want to generate pdf document?');">
                <i class="fas fa-print-alt"></i> Print Report
            </a>

            <a  type="button" class="btn btn-warning btn-sm btn-block" href="{% url 'EcoMan:analysis_comparison_to_json' pk_analysis_comparison=analysis_comparison.id %}" >Export JSON File </a>
            <button type="button" class="btn btn-warning btn-sm btn-block js-object-update" id="#modal-window-xl" data-url="{% url 'EcoMan:json_import_analysis_comparison_append' pk_analysis_comparison=analysis_comparison.id %}">
                Import JSON File
            </button>

        </div>
    </div>
</div>