EcoMan/urls.py
from django.urls import *
from django.urls import re_path as url
from django_keycloak.decorators import group_required_account_not_expired, check_keycloak_status, group_required
from website.security.url_decorators_for_database_content import *
from .Views import *
app_name = "EcoMan"
group_name ="/be_paramount/app-ecoman"
_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None, fi=None: _auth(project_security_check(f, app_name=a, model_name=m, field=fi))
_object = lambda f, a=None, m=None, fi=None: _auth(object_security_check(f, app_name=a, model_name=m, field=fi))
_owner = lambda f, a=None, m=None, fi=None: _auth(owner_security_check(f, app_name=a, model_name=m, field=fi))

urlpatterns = [


    url(r'index/$', _auth(index.as_view()), name ='index'),

    url(r'analysis_playground/welcome_screen/$', _auth(qlca_welcome_screen.as_view()), name ='qlca_welcome_screen'),
    url(r'analysis/welcome_screen$', _auth(qlca_analysis_welcome_screen.as_view()), name ='qlca_analysis_welcome_screen'),
    #lca part
    #url(r'^lcapart/create/$', _auth(lca_part_create_modal), name='lca_part_create_modal'),
    url(r'^lcapart/create/pk_analysis:(?P<pk_analysis>[0-9]*)/is_automotive:(?P<is_automotive>True|False)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_create_modal), name='lca_part_create_modal'),
    url(r'^lcapart/(?P<pk>[0-9]+)/update/is_automotive:(?P<is_automotive>True|False)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_update), name='lca_part_update'),
    url(r'^lcapart/(?P<pk>[0-9]+)/delete/$', _auth(lca_part_delete, required_roles = ['edag_worker'],), name='lca_part_delete'),

    #lca parts operations playground
    url(r'^lca_part_switch_analysis/source_analysis/(?P<pk_source_analysis>[0-9]+)/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_move), name='lca_part_move'),
    url(r'^lca_part_add_mirror/source_analysis/(?P<pk_source_analysis>[0-9]+)/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_add_mirror), name='lca_part_add_mirror'),
    url(r'^lca_part_remove_mirror/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_remove_mirror), name='lca_part_remove_mirror'),
    url(r'^(?P<pk_analysis>[0-9]+)/clone_lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(quick_part_clone), name='quick_part_clone'),


    #analysis_comparison_playgroud
    url(r'^analysis_comparison/(?P<pk>[0-9]+)/playgrounddetail/$', _auth(analysis_comparison_detail_view.as_view()), name ='analysis_comparison_detail_view'),
    url(r'^current/playgrounddetail/$', _auth(continue_analysis_comparison_detail_view), name ='continue_analysis_comparison_detail_view'),
    url(r'index/qlcaplayground/$', _auth(analysis_comparison_index_view.as_view()), name ='analysis_comparison_index_view'),
    #analysis_comparison #modal windows
    url(r'^analysis_playground/createandedit/$', _auth(analysis_comparison_create_and_edit), name='analysis_comparison_create_and_edit'),
    url(r'^analysis_playground/create/$', _auth(analysis_comparison_create), name='analysis_comparison_create'),
    url(r'^analysis_playground/(?P<pk>[0-9]+)/update/$', _auth(analysis_comparison_update), name='analysis_comparison_update'),
    url(r'^analysis_playground/(?P<pk>[0-9]+)/update_report_settings/$', _auth(analysis_comparison_report_update), name='analysis_comparison_report_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', _auth(analysis_comparison_delete, required_roles = ['edag_worker'],), name='analysis_comparison_delete'),

    # analysis
    url(r'index/analysis/$', _auth(analysis_index_view.as_view()), name='analysis_index_view'),
    url(r'^analysis/current/detail/$', _auth(continue_analysis_detail_view), name ='continue_analysis_detail_view'),

    url(r'^analysis/(?P<pk>[0-9]+)/playgroundonecolumn/$', _owner(analysis_detail_view.as_view(), a='EcoMan', m='Analysis'), name='analysis_detail_view'),

    #analysis #modal windows   
    url(r'^analysis/createandedit/$', _auth(analysis_create_and_edit), name='analysis_create_and_edit'),
    url(r'^analysis/(?P<pk>[0-9]+)/update/$', _auth(analysis_update), name='analysis_update'),
    url(r'^analysis/(?P<pk>[0-9]+)/delete/$', _auth(analysis_delete, required_roles = ['edag_worker'],), name='analysis_delete'),
    url(r'^analysis/(?P<pk>[0-9]+)/update_report_settings/$', _auth(analysis_settings_update), name='analysis_settings_update'),

    #analysis_comparison
    url(r'index/qlcacompare/$', _auth(analysis_index_view_compare.as_view()), name ='qlca_compare'),
    url(r'index/qlcacompare/create$', _auth(analysis_comparison_create_compare), name ='analysis_comparison_create_compare'),

    #support ticket
    url(r'^supportticket/create/$', _auth(lca_support_ticket_create_modal, required_roles = ['edag_worker'],), name='lca_support_ticket_create_modal'),

    #print playground report
    url(r'^(?P<pk>[0-9]+)/print/$', _auth(lca_comparison_print_reportlab), name='lca_comparison_print_reportlab'),
    
    #print playground report
    url(r'^analysis/(?P<pk>[0-9]+)/print/$', _auth(lca_analysis_print_reportlab), name='lca_analysis_print_reportlab'),

    #LCA Part lca_part_add_process
    url(r'^lca_part/(?P<pk_lca_part>[0-9]*)/addnewlcaprocess/lca_step/(?P<lca_step>[\w\-]+)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_add_process_instance), name='lca_part_add_process_instance'),

    url(r'^lca_part/(?P<pk>[0-9]*)/addnew:process_circularity/$', _auth(step1upstream_add_process_circularity), name='step1upstream_add_process_circularity'),
    url(r'^lca_part/(?P<pk>[0-9]*)/addnew:transport_circularity/$', _auth(step1upstream_add_transport_circularity), name='step1upstream_add_transport_circularity'),
    url(r'^lca_part/(?P<pk_lca_part>[0-9]*)/toggle_ispartreused/$', _auth(lcastep_ispartreused_status), name='lcastep_ispartreused_status'),

    #analysis modal
    url(r'^analysis_comparison/(?P<pk>[0-9]*)/addnew:utilisation/$', _auth(analysis_comparison_add_utilisation), name='analysis_comparison_add_utilisation'),
    url(r'^analysis/(?P<pk>[0-9]*)/addnew:utilisation/$', _auth(analysis_add_utilisation), name='analysis_add_utilisation'),
    #instance process
    url(r'^material_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)$', _auth(material_process_instance_update), name='material_process_instance_update'),
    url(r'^processing_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)/update/$', _auth(processing_process_instance_update), name='processing_process_instance_update'),
    url(r'^transport_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)$', _auth(transport_process_instance_update), name='transport_process_instance_update'),
    url(r'^instance_lca_process/(?P<pk>[0-9]+)/delete/$', _auth(instance_idemat_process_delete), name='instance_idemat_process_delete'),
    url(r'^lca_part/(?P<pk_process_instance>[0-9]*)/process_instance_is_active/$', _auth(process_instance_is_active), name='process_instance_is_active'),

    #instance_utilisation_process   (word instance should be removed - it is not the same as with idemate process and instance idemat process)

    url(r'^utilisation_process/create/analysis:(?P<pk_analysis>[0-9]*)$', _auth(utilisation_instance_process_create), name='utilisation_instance_process_create'),
    url(r'^utilisation_process/create/$', _auth(utilisation_instance_process_create), name='utilisation_instance_process_create'),
    url(r'^utilisation_process/(?P<pk>[0-9]+)/delete/$', _auth(utilisation_instance_process_delete), name='utilisation_instance_process_delete'),
    url(r'^utilistaion_process/(?P<pk_instance>[0-9]*)/update/$', _auth(utilisation_instance_process_update), name='utilisation_instance_process_update'),

    #instance_circularity_process
    url(r'^circularity_process/(?P<pk_circularity_process>[0-9]*)/update/$', _auth(circularity_process_update), name='circularity_process_update'),

    #LCA Database
    url(r'^lca_db/(?P<pk>[0-9]+)/processlist/$', _auth(LcaProcessListView.as_view()), name='lca_process_list'),
    
    url(r'^lca_db/open/list/$', _auth(open_database_index_view.as_view()), name='open_database_index_view'),
    url(r'^lca_db/organisation/list/$', _auth(edag_database_index_view.as_view()), name='edag_database_index_view'),
    url(r'^lca_db/project/list/$', _auth(project_database_index_view.as_view()), name='project_database_index_view'),
    
    url(r'^lca_db/create/$', _auth(lca_db_create), name='lca_db_create'),
    url(r'^lca_db/(?P<pk>[0-9]+)/update/$', _auth(lca_db_update), name='lca_db_update'),
    url(r'^lca_db/(?P<pk>[0-9]+)/importexcel/$', _auth(lca_db_import_excel, required_roles = ['edag_worker']), name='lca_db_import_excel'),
    url(r'^lca_db/(?P<pk>[0-9]+)/exportexcel/$', _auth(lca_db_export_excel, required_roles = ['edag_worker']), name='lca_db_export_excel'),

    url(r'^lca_db/(?P<pk>[0-9]+)/delete/$', _auth(lca_db_delete, required_roles = ['edag_worker'], required_groups=[group_name + 'user-professional']), name='lca_db_delete'),
    url(r'^lca_db/(?P<pk>[0-9]+)/restore/$', _auth(lca_db_restore, required_roles = ['edag_worker'], required_groups=[group_name + 'user-professional']), name='lca_db_restore'),
    url(r'^lca_db/create/excel_import$', _auth(lca_db_create, required_roles = ['edag_worker']), name='lca_db_create'),
    url(r'^lca_db/download_lca_template/$', _auth(lca_database_template_download), name='lca_database_template_download'),

    #lca_process

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django_keycloak.decorators import group_required, check_keycloak_status
from django_keycloak.keycloak_manager import keycloak_manager
from django.urls import path, include
from django.urls import re_path as url
from django.views.generic import TemplateView
from website.views import *
from website.views.modal import *
from CatiaFramework.urls.urls_main import urls_modal

from website.security.url_decorators_for_database_content import *

admin.site.site_header = 'BE PARAMOUNT admin page'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'HTML title from adminsitration' # default: "Django site admin"


# group_name_professional ="/be_paramount/user-professional"
group_name ="/be_paramount"
app_name = 'website'
_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None: _auth(project_security_check(f, app_name=a, model_name=m))
_object = lambda f, a=None, m=None: _auth(object_security_check(f, app_name=a, model_name=m))
_owner = lambda f, a=None, m=None: _auth(owner_security_check(f, app_name=a, model_name=m))





'''
LOAD appurlspatterns based on configured system (env file)
'''

app_url_patterns = list()

for app in settings.GROUPS.values():
    match app:
        case 'boltman':
            app_url_patterns.append(path('bolt/', include('BoltMan.urls')))
        case 'matman':
            app_url_patterns.append(path('material/', include('MatMan.urls')))
        case 'conceptman':
            app_url_patterns.append(path('concept/', include('ConceptMan.urls')))            
        case 'ecoman':
            app_url_patterns.append(path('qlca/', include('EcoMan.urls')))
        case 'catfrm':
            app_url_patterns.append(path('catiaframework/', include('CatiaFramework.urls')),)
        case 'normman':
            app_url_patterns.append(path('shared_components/', include('NormMan.urls')))


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_home, name='redirect_to_home'),
    url(r'home/$', _auth(index.as_view()), name ='home'),
    url(r'err/not_in_group$', TemplateView.as_view(template_name='website/not_in_group_err.html'), name ='not_in_group'),
    url(r'err/account_expired$', TemplateView.as_view(template_name='website/account_expired_err.html'), name ='account_expired'),

    # Application views
    # ToDo: Separate for future

    # Project
    url(r'^project/create/$', _auth(project_create, required_roles=["edag_worker"], ), name='project_create'),
    url(r'^project/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_update), name='project_update'),
    url(r'^project/(?P<uuid>[0-9a-t\-]{32,})/delete/$', _auth(project_delete), name='project_delete'),
    # Vehicle
    url(r'^vehicles/create/$', _auth(vehicle_create), name='vehicle_create'),
    url(r'^vehicles/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(vehicle_update), name='vehicle_update'),
    url(r'^vehicles/(?P<uuid>[0-9a-t\-]{32,})/delete/$', _auth(vehicle_delete), name='vehicle_delete'),
    # Production rate
    url(r'^production_rate/(?P<pk>[0-9]+)/update/$', _auth(production_rate_update), name='production_rate_update'),
    # Userproject
    url(r'^project_user_update/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_user_update), name='project_user_update'),
    url(r'^project_user_select_current_project/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_user_select_current_project, required_roles=["edag_worker"]), name='project_user_select_current_project'),
    url(r'^project_update_authorised_users/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_update_authorised_users, required_roles=["edag_worker"]), name='project_update_authorised_users'),
    # Info modal
    url(r'^info/concept/$', _auth(info_concept), name='info_concept'),
    url(r'load-project-users/$', _auth(load_project_users), name='load_project_users'),
    
    #Token
    url(r'^tokens/create/component_uuid:(?P<uuid_component>[0-9a-t\-]{32,})$', _auth(token_create_modal), name='token_create_modal'),


    # Websocket
    path('rooms/', index_view, name='chat-index'),
    path('rooms/<str:room_name>/', room_view, name='chat-room'),
    # Keycloak redirect from all application endpoints
    path('user/login/', lambda request: redirect(f"{request.scheme}://{request.headers['Host']}/keycloak/login"), name='login_redirect'),
    path('keycloak/login/', keycloak_manager.keycloak_admin_redirect, name='keycloak_admin_redirect'),
    # Keycloak login
    path('home/keycloak/expired_login/', keycloak_manager.expired_login, name='expired_login'),    
    path('keycloak/login/callback/', keycloak_manager.keycloak_login, name='keycloak_login'),
    path('keycloak/logout/', keycloak_manager.keycloak_logout, name='keycloak_logout'),    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + app_url_patterns

EcoMan/models/lca_circularity_process.py
from django.db import models
from EcoMan.models import Lca_Part
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save , pre_save  
from website.generate_pk import generate_pk
from django.conf import settings
from website.models import Vehicle
from EcoMan.models import Lca_Part
from EcoMan.models import Analysis
from EcoMan.scripts import get_random_color
from django.core.validators import MinValueValidator, MaxValueValidator
NONNEGATIVE_VALIDATOR = [MinValueValidator(0),]
class Circularity_Process(models.Model):
    id = models.CharField(default=generate_pk, primary_key=True, max_length=255, unique=True)    
    name = models.CharField(max_length=100,  default= 'Not defined', editable=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey("EcoMan.ProjectUser_EcoMan_Ref", models.SET_NULL, blank=True,null=True,)


    #specific elements
    
    lifetimeinkm = models.IntegerField(editable=True, verbose_name= "Part lifetime in km", default = 150000, blank=True, null=True, validators=NONNEGATIVE_VALIDATOR,) 
    ispartreused = models.BooleanField(default =False,)    
    notes = models.CharField(max_length=100,  default= 'Put your comment here...', editable=True, blank=True)

    service_intervals =[] # non database property (will not be saved in database)

    def check_bonusmalus(self, vehicle, tacho, calc_interval): 
        lca_step = Lca_Part.objects.filter(circularity_process_model__pk=self.pk).get()
         
        service_modulo = tacho % self.lifetimeinkm #check how far away we are from the service interval

        if service_modulo < calc_interval & tacho > 0.1 * calc_interval: #get rid of interval at tacho = 0
            bonusmalus = True
        else:
            bonusmalus = False

        return bonusmalus

    class Meta:
        app_label = 'EcoMan'
    def __str__(self):
        return str(self.name) 

    @receiver(pre_save, sender=Lca_Part)
    def create_circularity_process(sender, instance,  **kwargs):
        if instance._state.adding:
              Circularity_Process.objects.create(lca_part = instance)
        else:
            if hasattr(instance, 'circularity_process_model') and instance.circularity_process_model is None:
                  Circularity_Process.objects.create(lca_part = instance)

EcoMan/templates/modals/analysis_comparison/analysis_comparison_create_modal.html
{% load widget_tweaks %}

<form method="post" action="{% url 'EcoMan:analysis_comparison_create_and_edit' %}" class="js-object-create-form">
  {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header bg-warning text-white">
              <h5 class="modal-title" id="exampleModalLongTitle"><b>Create new QLCA for two concepts</b></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <div class="modal-body">

            {% include 'modals/analysis_comparison/modal_template_two_column_create_form.html' %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Add to database</button>
        </div>
      </div>
</form>


<script>
    $(document).ready(function(){
      $('[data-toggle="popover"]').popover();
    });
</script>

EcoMan/templates/modals/analysis_comparison/analysis_comparison_delete_modal.html
<form method="post" id="#modal-window" action="{% url 'EcoMan:analysis_comparison_delete' qlca_analysis.id %}" class="js-object-delete-form">
    {% csrf_token %}
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle"><b>Confirm A-B Assessment deletion</b></h5>
            </div>
            <div class="modal-body">
                <p class="lead">Are you sure you want to delete this QLCA Playgrund Analysis? <strong>{{ part.name }}</strong></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

EcoMan/templates/modals/analysis_comparison/analysis_comparison_import_JSON_modal.html
{% load widget_tweaks %}

<form method="post" enctype="multipart/form-data" action="{% url 'EcoMan:json_import_analysis_comparison_create_new' %}" class="js-object-create-form" nonvalidate>
  {% csrf_token %}
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle"><b>Import JSON</b></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <div class="modal-body">


            {% include 'modals/analysis_comparison/modal_template_two_column_importJSON_form.html' %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" name="btnPreview" id="btnPreview">Preview</button>
          <button type="submit" class="btn btn-primary" name="btnSave">Add to database</button>
        </div>
      </div>
    </div>
</form>


<script>

  $(document).ready(function(){
      $('[data-toggle="popover"]').popover();
  });

  var previewClicked = false;

  $("#btnPreview").on('click', function() {
    previewClicked = true;
    console.log("previewTrue");
  });

</script>

EcoMan/templates/modals/analysis_comparison/analysis_comparison_import_json_append_modal.html
{% load widget_tweaks %}

<form method="post" id="#modal-window" action="{% url 'EcoMan:json_import_analysis_comparison_append' form.instance.pk %}" enctype="multipart/form-data" class="js-object-update-form">
  {% csrf_token %}
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle"><b>Import data from json File</b></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <div class="modal-body">
          {% include 'modals/modal_template_form.html' %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </div>
</form>

EcoMan/templates/modals/analysis_comparison/analysis_comparison_report_update_modal.html
{% load widget_tweaks %}
<form method="post" id="#modal-form" action="{% url 'EcoMan:analysis_comparison_report_update' form.instance.pk %}" class="js-object-update-form" nonvalidate>
  {% csrf_token %}
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle"><b>Report Settings</b></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <div class="modal-body">
          {% include 'modals/modal_template_form.html' %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </div>
    </div>
</form>

EcoMan/templates/modals/analysis_comparison/analysis_comparison_update_modal.html
{% load widget_tweaks %}
{% load form_tags %}
<form method="post" action="{% url 'EcoMan:analysis_comparison_update' form.instance.pk %}" class="js-object-update-form" novalidate>
  {% csrf_token %}
      <div class="modal-content">
        <div class="modal-header bg-warning text-white">
              <h5 class="modal-title" id="exampleModalLongTitle"><b>Edit Assessment Header Data</b></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <div class="modal-body">


            {% include 'modals/analysis_comparison/modal_template_two_column_update_form.html' %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </div>
</form>


<script>
    $(document).ready(function(){
      $('[data-toggle="popover"]').popover();
    });
</script>



<script>

var checkbox1 = document.getElementById('id_is_automotive');
var otherCheckboxes = [
      document.getElementById('id_include_circularity'),
      document.getElementById('id_include_utilisation'),
  ];


    // Function to initialize checkbox states
    function initializeCheckboxes() {
        if (!checkbox1.checked) {
            otherCheckboxes.forEach(checkbox => {
                checkbox.checked = false;
                checkbox.disabled = true;
                checkbox.parentElement.classList.add('disabled');
            });
        }
    }
    // Initialize checkboxes on page load
    initializeCheckboxes();
    checkbox1.addEventListener('change', function() {
        if (checkbox1.checked) {
            otherCheckboxes.forEach(checkbox => {
                checkbox.checked = false;
                checkbox.disabled = false; // Enable other checkboxes
                checkbox.parentElement.classList.remove('disabled'); // Remove disabled class
            });
        } else {
            otherCheckboxes.forEach(checkbox => {
                checkbox.disabled = true; // Disable other checkboxes
                checkbox.checked = false; // Uncheck other checkboxes
                checkbox.parentElement.classList.add('disabled'); // Add disabled class
            });
        }
  });

</script>

EcoMan/templates/modals/analysis_comparison/modal_template_two_column_importJSON_form.html
{% load widget_tweaks %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group{% if field.errors %} has-error{% endif %}">

                        <label for="id_JSON_file">Source JSON File</label>
                        {{ form.JSON_file|add_class:"form-control"}}
                        <span class="text-danger">{{ form.JSON_file.errors|striptags }}</span>


                        <label for="id_name">Name</label>
                        {{ form.name|add_class:"form-control"}}
                        <span class="text-danger">{{ form.name.errors|striptags }}</span>

                        <label for="id_tosandbox">To Sandbox (playground will be imported to user sandbox project) </label>
                        {{ form.tosandbox|add_class:"form-control"}}
                        <span class="text-danger">{{ form.tosandbox.errors|striptags }}</span>

                        <label for="id_is_public">Is Public</label>
                        {{ form.is_public|add_class:"form-control"}}
                        <span class="text-danger">{{ form.is_public.errors|striptags }}</span>

                        <label for="id_project_model">Project</label>
                        {{ form.project_model|add_class:"form-control"}}
                        <span class="text-danger">{{ form.project_model.errors|striptags }}</span>

                    </div>
                </div>

                <div class="col-md-6" id="json_import_preview" data-process-url="{% url 'EcoMan:load_json_preview' %}">

                </div>


            </div>
            <div class="row" id="json_import_diff"></div>
        </div>
    </div>
</div>