EcoMan/urls.py
from django.urls import *
from django.urls import re_path as url
from django_keycloak.decorators import group_required_account_not_expired, check_keycloak_status, group_required
from website.security.url_decorators_for_database_content import *
from .Views import *
app_name = "EcoMan"
group_name ="/be_paramount/app-ecoman"
_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None, fi=None: _auth(project_security_check(f, app_name=a, model_name=m, field=fi))
_object = lambda f, a=None, m=None, fi=None: _auth(object_security_check(f, app_name=a, model_name=m, field=fi))
_owner = lambda f, a=None, m=None, fi=None: _auth(owner_security_check(f, app_name=a, model_name=m, field=fi))

urlpatterns = [


    url(r'index/$', _auth(index.as_view()), name ='index'),

    url(r'analysis_playground/welcome_screen/$', _auth(qlca_welcome_screen.as_view()), name ='qlca_welcome_screen'),
    url(r'analysis/welcome_screen$', _auth(qlca_analysis_welcome_screen.as_view()), name ='qlca_analysis_welcome_screen'),
    #lca part
    #url(r'^lcapart/create/$', _auth(lca_part_create_modal), name='lca_part_create_modal'),
    url(r'^lcapart/create/pk_analysis:(?P<pk_analysis>[0-9]*)/is_automotive:(?P<is_automotive>True|False)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_create_modal), name='lca_part_create_modal'),
    url(r'^lcapart/(?P<pk>[0-9]+)/update/is_automotive:(?P<is_automotive>True|False)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_update), name='lca_part_update'),
    url(r'^lcapart/(?P<pk>[0-9]+)/delete/$', _auth(lca_part_delete, required_roles = ['edag_worker'],), name='lca_part_delete'),

    #lca parts operations playground
    url(r'^lca_part_switch_analysis/source_analysis/(?P<pk_source_analysis>[0-9]+)/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_move), name='lca_part_move'),
    url(r'^lca_part_add_mirror/source_analysis/(?P<pk_source_analysis>[0-9]+)/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_add_mirror), name='lca_part_add_mirror'),
    url(r'^lca_part_remove_mirror/target_analysis/(?P<pk_target_analysis>[0-9]+)/lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(lca_part_remove_mirror), name='lca_part_remove_mirror'),
    url(r'^(?P<pk_analysis>[0-9]+)/clone_lca_part/(?P<pk_lca_part>[0-9]+)$', _auth(quick_part_clone), name='quick_part_clone'),


    #analysis_comparison_playgroud
    url(r'^analysis_comparison/(?P<pk>[0-9]+)/playgrounddetail/$', _auth(analysis_comparison_detail_view.as_view()), name ='analysis_comparison_detail_view'),
    url(r'^current/playgrounddetail/$', _auth(continue_analysis_comparison_detail_view), name ='continue_analysis_comparison_detail_view'),
    url(r'index/qlcaplayground/$', _auth(analysis_comparison_index_view.as_view()), name ='analysis_comparison_index_view'),
    #analysis_comparison #modal windows
    url(r'^analysis_playground/createandedit/$', _auth(analysis_comparison_create_and_edit), name='analysis_comparison_create_and_edit'),
    url(r'^analysis_playground/create/$', _auth(analysis_comparison_create), name='analysis_comparison_create'),
    url(r'^analysis_playground/(?P<pk>[0-9]+)/update/$', _auth(analysis_comparison_update), name='analysis_comparison_update'),
    url(r'^analysis_playground/(?P<pk>[0-9]+)/update_report_settings/$', _auth(analysis_comparison_report_update), name='analysis_comparison_report_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', _auth(analysis_comparison_delete, required_roles = ['edag_worker'],), name='analysis_comparison_delete'),

    # analysis
    url(r'index/analysis/$', _auth(analysis_index_view.as_view()), name='analysis_index_view'),
    url(r'^analysis/current/detail/$', _auth(continue_analysis_detail_view), name ='continue_analysis_detail_view'),

    url(r'^analysis/(?P<pk>[0-9]+)/playgroundonecolumn/$', _owner(analysis_detail_view.as_view(), a='EcoMan', m='Analysis'), name='analysis_detail_view'),

    #analysis #modal windows   
    url(r'^analysis/createandedit/$', _auth(analysis_create_and_edit), name='analysis_create_and_edit'),
    url(r'^analysis/(?P<pk>[0-9]+)/update/$', _auth(analysis_update), name='analysis_update'),
    url(r'^analysis/(?P<pk>[0-9]+)/delete/$', _auth(analysis_delete, required_roles = ['edag_worker'],), name='analysis_delete'),
    url(r'^analysis/(?P<pk>[0-9]+)/update_report_settings/$', _auth(analysis_settings_update), name='analysis_settings_update'),

    #analysis_comparison
    url(r'index/qlcacompare/$', _auth(analysis_index_view_compare.as_view()), name ='qlca_compare'),
    url(r'index/qlcacompare/create$', _auth(analysis_comparison_create_compare), name ='analysis_comparison_create_compare'),

    #support ticket
    url(r'^supportticket/create/$', _auth(lca_support_ticket_create_modal, required_roles = ['edag_worker'],), name='lca_support_ticket_create_modal'),

    #print playground report
    url(r'^(?P<pk>[0-9]+)/print/$', _auth(lca_comparison_print_reportlab), name='lca_comparison_print_reportlab'),
    
    #print playground report
    url(r'^analysis/(?P<pk>[0-9]+)/print/$', _auth(lca_analysis_print_reportlab), name='lca_analysis_print_reportlab'),

    #LCA Part lca_part_add_process
    url(r'^lca_part/(?P<pk_lca_part>[0-9]*)/addnewlcaprocess/lca_step/(?P<lca_step>[\w\-]+)/weight_unit:(?P<weight_unit>[a-zA-Z]+)$', _auth(lca_part_add_process_instance), name='lca_part_add_process_instance'),

    url(r'^lca_part/(?P<pk>[0-9]*)/addnew:process_circularity/$', _auth(step1upstream_add_process_circularity), name='step1upstream_add_process_circularity'),
    url(r'^lca_part/(?P<pk>[0-9]*)/addnew:transport_circularity/$', _auth(step1upstream_add_transport_circularity), name='step1upstream_add_transport_circularity'),
    url(r'^lca_part/(?P<pk_lca_part>[0-9]*)/toggle_ispartreused/$', _auth(lcastep_ispartreused_status), name='lcastep_ispartreused_status'),

    #analysis modal
    url(r'^analysis_comparison/(?P<pk>[0-9]*)/addnew:utilisation/$', _auth(analysis_comparison_add_utilisation), name='analysis_comparison_add_utilisation'),
    url(r'^analysis/(?P<pk>[0-9]*)/addnew:utilisation/$', _auth(analysis_add_utilisation), name='analysis_add_utilisation'),
    #instance process
    url(r'^material_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)$', _auth(material_process_instance_update), name='material_process_instance_update'),
    url(r'^processing_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)/update/$', _auth(processing_process_instance_update), name='processing_process_instance_update'),
    url(r'^transport_instance_lca_process/(?P<pk_instance>[0-9]*)/update/weight_unit:(?P<weight_unit>[a-zA-Z]+)/weight_decimals:(?P<weight_decimals>[0-9]*)$', _auth(transport_process_instance_update), name='transport_process_instance_update'),
    url(r'^instance_lca_process/(?P<pk>[0-9]+)/delete/$', _auth(instance_idemat_process_delete), name='instance_idemat_process_delete'),
    url(r'^lca_part/(?P<pk_process_instance>[0-9]*)/process_instance_is_active/$', _auth(process_instance_is_active), name='process_instance_is_active'),

    #instance_utilisation_process   (word instance should be removed - it is not the same as with idemate process and instance idemat process)

    url(r'^utilisation_process/create/analysis:(?P<pk_analysis>[0-9]*)$', _auth(utilisation_instance_process_create), name='utilisation_instance_process_create'),
    url(r'^utilisation_process/create/$', _auth(utilisation_instance_process_create), name='utilisation_instance_process_create'),
    url(r'^utilisation_process/(?P<pk>[0-9]+)/delete/$', _auth(utilisation_instance_process_delete), name='utilisation_instance_process_delete'),
    url(r'^utilistaion_process/(?P<pk_instance>[0-9]*)/update/$', _auth(utilisation_instance_process_update), name='utilisation_instance_process_update'),

    #instance_circularity_process
    url(r'^circularity_process/(?P<pk_circularity_process>[0-9]*)/update/$', _auth(circularity_process_update), name='circularity_process_update'),

    #LCA Database
    url(r'^lca_db/(?P<pk>[0-9]+)/processlist/$', _auth(LcaProcessListView.as_view()), name='lca_process_list'),
    
    url(r'^lca_db/open/list/$', _auth(open_database_index_view.as_view()), name='open_database_index_view'),
    url(r'^lca_db/organisation/list/$', _auth(edag_database_index_view.as_view()), name='edag_database_index_view'),
    url(r'^lca_db/project/list/$', _auth(project_database_index_view.as_view()), name='project_database_index_view'),
    
    url(r'^lca_db/create/$', _auth(lca_db_create), name='lca_db_create'),
    url(r'^lca_db/(?P<pk>[0-9]+)/update/$', _auth(lca_db_update), name='lca_db_update'),
    url(r'^lca_db/(?P<pk>[0-9]+)/importexcel/$', _auth(lca_db_import_excel, required_roles = ['edag_worker']), name='lca_db_import_excel'),
    url(r'^lca_db/(?P<pk>[0-9]+)/exportexcel/$', _auth(lca_db_export_excel, required_roles = ['edag_worker']), name='lca_db_export_excel'),

    url(r'^lca_db/(?P<pk>[0-9]+)/delete/$', _auth(lca_db_delete, required_roles = ['edag_worker'], required_groups=[group_name + 'user-professional']), name='lca_db_delete'),
    url(r'^lca_db/(?P<pk>[0-9]+)/restore/$', _auth(lca_db_restore, required_roles = ['edag_worker'], required_groups=[group_name + 'user-professional']), name='lca_db_restore'),
    url(r'^lca_db/create/excel_import$', _auth(lca_db_create, required_roles = ['edag_worker']), name='lca_db_create'),
    url(r'^lca_db/download_lca_template/$', _auth(lca_database_template_download), name='lca_database_template_download'),

    #lca_process

MatMan/urls.py
from django.urls import re_path as url
from django_keycloak.decorators import group_required, check_keycloak_status
from website.security.url_decorators_for_database_content import *
from .Views import *
from .Views.modal import *

app_name = "MatMan"
group_name ="/be_paramount/app-matman"
_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None, fi=None: _auth(project_security_check(f, app_name=a, model_name=m, field=fi))
_object = lambda f, a=None, m=None, fi=None: _auth(object_security_check(f, app_name=a, model_name=m, field=fi))
_owner = lambda f, a=None, m=None, fi=None: _auth(owner_security_check(f, app_name=a, model_name=m, field=fi))

_auth = lambda f: group_required(f, group_name = "/be_paramount/app-matman")

urlpatterns = [


url(r'index/$', _auth(index.as_view()), name ='index_materialgroups'),
url(r'index/materialgroups/metals$', _auth(index_metals.as_view()), name ='index_metals'),

url(r'index/materialgroups/metals/ferrous/$', _auth(MetalFerrousListView.as_view()), name ='list_metalferrous'),   
url(r'index/materialgroups/metals/nonferrous/$', _auth(MetalNonFerrousListView.as_view()), name ='list_metalnonferrous'),   
url(r'index/materialgroups/plastic/$', _auth(PlasticListView.as_view()), name ='list_plastic'),  
url(r'index/materialgroups/ceramic/$', _auth(CeramicListView.as_view()), name ='list_ceramic'),  
url(r'index/materialgroups/composite/$', _auth(CompositeListView.as_view()), name ='list_composite'),  
url(r'index/materialgroups/special/$', _auth(SpecialListView.as_view()), name ='list_special'),  

#engineering_material
url(r'^engineering_material/create/$', _auth(EngineeringMaterial_create), name='engineeringmaterial_create'),
url(r'^engineering_material/(?P<pk>[0-9]+)/update/$', _auth(EngineeringMaterial_update), name='engineeringmaterial_update'),
url(r'^engineering_material/(?P<pk>[0-9]+)/delete/$', _auth(EngineeringMaterial_delete), name='engineeringmaterial_delete'),



url(r'^engineering_material/(?P<pk>[0-9]+)/detail/$', _auth(EngineeringMaterialDetailView.as_view()), name ='engineeringmaterial_detailview'),

]

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django_keycloak.decorators import group_required, check_keycloak_status
from django_keycloak.keycloak_manager import keycloak_manager
from django.urls import path, include
from django.urls import re_path as url
from django.views.generic import TemplateView
from website.views import *
from website.views.modal import *
from CatiaFramework.urls.urls_main import urls_modal

from website.security.url_decorators_for_database_content import *

admin.site.site_header = 'BE PARAMOUNT admin page'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'HTML title from adminsitration' # default: "Django site admin"


# group_name_professional ="/be_paramount/user-professional"
group_name ="/be_paramount"
app_name = 'website'
_auth = lambda f,required_groups = None, required_roles = None: group_required(check_keycloak_status(f), app_group=group_name,  group_names = required_groups, role_names = required_roles)
_project = lambda f, a=None, m=None: _auth(project_security_check(f, app_name=a, model_name=m))
_object = lambda f, a=None, m=None: _auth(object_security_check(f, app_name=a, model_name=m))
_owner = lambda f, a=None, m=None: _auth(owner_security_check(f, app_name=a, model_name=m))





'''
LOAD appurlspatterns based on configured system (env file)
'''

app_url_patterns = list()

for app in settings.GROUPS.values():
    match app:
        case 'boltman':
            app_url_patterns.append(path('bolt/', include('BoltMan.urls')))
        case 'matman':
            app_url_patterns.append(path('material/', include('MatMan.urls')))
        case 'conceptman':
            app_url_patterns.append(path('concept/', include('ConceptMan.urls')))            
        case 'ecoman':
            app_url_patterns.append(path('qlca/', include('EcoMan.urls')))
        case 'catfrm':
            app_url_patterns.append(path('catiaframework/', include('CatiaFramework.urls')),)
        case 'normman':
            app_url_patterns.append(path('shared_components/', include('NormMan.urls')))


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', redirect_to_home, name='redirect_to_home'),
    url(r'home/$', _auth(index.as_view()), name ='home'),
    url(r'err/not_in_group$', TemplateView.as_view(template_name='website/not_in_group_err.html'), name ='not_in_group'),
    url(r'err/account_expired$', TemplateView.as_view(template_name='website/account_expired_err.html'), name ='account_expired'),

    # Application views
    # ToDo: Separate for future

    # Project
    url(r'^project/create/$', _auth(project_create, required_roles=["edag_worker"], ), name='project_create'),
    url(r'^project/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_update), name='project_update'),
    url(r'^project/(?P<uuid>[0-9a-t\-]{32,})/delete/$', _auth(project_delete), name='project_delete'),
    # Vehicle
    url(r'^vehicles/create/$', _auth(vehicle_create), name='vehicle_create'),
    url(r'^vehicles/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(vehicle_update), name='vehicle_update'),
    url(r'^vehicles/(?P<uuid>[0-9a-t\-]{32,})/delete/$', _auth(vehicle_delete), name='vehicle_delete'),
    # Production rate
    url(r'^production_rate/(?P<pk>[0-9]+)/update/$', _auth(production_rate_update), name='production_rate_update'),
    # Userproject
    url(r'^project_user_update/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_user_update), name='project_user_update'),
    url(r'^project_user_select_current_project/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_user_select_current_project, required_roles=["edag_worker"]), name='project_user_select_current_project'),
    url(r'^project_update_authorised_users/(?P<uuid>[0-9a-t\-]{32,})/update/$', _auth(project_update_authorised_users, required_roles=["edag_worker"]), name='project_update_authorised_users'),
    # Info modal
    url(r'^info/concept/$', _auth(info_concept), name='info_concept'),
    url(r'load-project-users/$', _auth(load_project_users), name='load_project_users'),
    
    #Token
    url(r'^tokens/create/component_uuid:(?P<uuid_component>[0-9a-t\-]{32,})$', _auth(token_create_modal), name='token_create_modal'),


    # Websocket
    path('rooms/', index_view, name='chat-index'),
    path('rooms/<str:room_name>/', room_view, name='chat-room'),
    # Keycloak redirect from all application endpoints
    path('user/login/', lambda request: redirect(f"{request.scheme}://{request.headers['Host']}/keycloak/login"), name='login_redirect'),
    path('keycloak/login/', keycloak_manager.keycloak_admin_redirect, name='keycloak_admin_redirect'),
    # Keycloak login
    path('home/keycloak/expired_login/', keycloak_manager.expired_login, name='expired_login'),    
    path('keycloak/login/callback/', keycloak_manager.keycloak_login, name='keycloak_login'),
    path('keycloak/logout/', keycloak_manager.keycloak_logout, name='keycloak_logout'),    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + app_url_patterns

MatMan/models.py
from django.db import models

# Create your models here.

MatMan/forms.py
from MatMan.models import Engineering_Material


from django.forms import ModelForm
from django import forms


#class UserForm(forms.ModelForm):
  #  password = forms.CharField(widget=forms.PasswordInput)

  #  class Meta:
  #      model = User
  #      fields = ['username', 'email', 'password']


class EngineeringMaterialForm(forms.ModelForm):
    class Meta:
        model = Engineering_Material
        fields = '__all__'
        exclude = ('created_at', 'updated_at', 'user' , 'id')  

MatMan/templates/MatMan/base.html
{% extends 'website/base.html' %}
{% load static %}

{% block AppIcon %}
<a class="navbar-brand" href="{% url 'MatMan:index_materialgroups' %}">
    <span><img src="{% static 'MatMan/images/MatMan_Ico.png' %}" alt="Logo" ></span>
    MatMan
</a>
{% endblock AppIcon %}


{% block NavItems %}

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Add Material Item
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                <a class="nav-link js-engineeringmaterial-create" href="#" data-url="{% url 'MatMan:engineeringmaterial_create' %}">New material </a>

            </div>
        </li>


    </ul>
</div>
{% endblock NavItems %}

{% block Apps %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-10">
                    <div class="row">
                        <div class="col-md-12">

                            {% block Cards %}
                            {% endblock Cards %}
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    {% include "website/current_project.html" %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock Apps %}

MatMan/templates/MatMan/index_materialgroups.html
{% extends 'MatMan/base.html' %}
{% load static %}

{% block Cards %}

<div class="container-fluid ">
    <div class="row">
        <div class="col-md-10 border-right">
            <div class="row">
                <div class="card  mx-3 my-3" style="width: 12rem;">
                    <img class="card-img-top" src="{% static 'MatMan/images/Metals_Ico.png' %}" alt="Card image cap">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Metals</h5>
                        <p class="card-text">Ferrous or Non Ferrous</p>
                        <div class="container-fluid" style="margin-top: auto;">
                            <div class="row">
                                <a href="{% url 'MatMan:index_metals'%}" class="btn btn-warning btn-lg btn-block" role="button" aria-disabled="true">View</a>
                                <a href="#" class="btn btn-info btn-lg btn-block" role="button" aria-disabled="true">Info</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card  mx-3 my-3" style="width: 12rem;">
                    <img class="card-img-top" src="{% static 'MatMan/images/Plastics_Ico.png' %}" alt="Card image cap">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Plastics</h5>
                        <p class="card-text">Thermosets or ThermoPlastics</p>
                        <div class="container-fluid" style="margin-top: auto;">
                            <div class="row">
                                <a href="{% url 'MatMan:list_plastic'%}" class="btn btn-warning btn-lg btn-block " role="button" aria-disabled="true">View</a>
                                <a href="#" class="btn btn-info btn-lg btn-block" role="button" aria-disabled="true">Info</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card  mx-3 my-3" style="width: 12rem;">
                    <img class="card-img-top" src="{% static 'MatMan/images/Ceramics_Ico.png' %}" alt="Card image cap">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Ceramics</h5>
                        <p class="card-text">Neither metallic nor organic </p>
                        <div class="container-fluid" style="margin-top: auto;">
                            <div class="row">
                                <a href="{% url 'MatMan:list_ceramic'%}" class="btn btn-warning btn-lg btn-block " role="button" aria-disabled="true">View</a>
                                <a href="#" class="btn btn-info btn-lg btn-block" role="button" aria-disabled="true">Info</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card  mx-3 my-3" style="width: 12rem;">
                    <img class="card-img-top" src="{% static 'MatMan/images/Composites_Ico.png' %}" alt="Card image cap">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Composites</h5>
                        <p class="card-text">Made of two or more principal materials </p>
                        <div class="container-fluid" style="margin-top: auto;">
                            <div class="row">
                                <a href="{% url 'MatMan:list_composite'%}" class="btn btn-warning btn-lg btn-block " role="button" aria-disabled="true">View</a>
                                <a href="#" class="btn btn-info btn-lg btn-block" role="button" aria-disabled="true">Info</a>
                            </div>
                        </div>
                    </div>
                </div>

                <<div class="card  mx-3 my-3" style="width: 12rem;">
                    <img class="card-img-top" src="{% static 'MatMan/images/Special_Ico.png' %}" alt="Card image cap">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Special</h5>
                        <p class="card-text">Bio Based, inteligent or of very specific application </p>
                        <div class="container-fluid" style="margin-top: auto;">
                            <div class="row">
                                <a href="{% url 'MatMan:list_special'%}" class="btn btn-warning btn-lg btn-block " role="button" aria-disabled="true">View</a>
                                <a href="#" class="btn btn-info btn-lg btn-block" role="button" aria-disabled="true">Info</a>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>

    </div>
</div>

{% endblock Cards %}

MatMan/templates/MatMan/index_metals.html
{% extends 'MatMan/base.html' %}
{% load static %}

{% block Cards %}

<div class="container-fluid ">
    <div class="row">
        <div class="col-md-10 border-right">
            <div class="row">
                <div class="card  mx-3 my-3" style="width: 12rem;">
                    <img class="card-img-top" src="{% static 'MatMan/images/Ferrous_Ico.png' %}" alt="Card image cap">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Ferrous</h5>
                        <p class="card-text">Cast Irons<br>Carbon Steels<br>Alloy Steels<br>Stainless Steels</p>
                        <div class="container-fluid" style="margin-top: auto;">
                            <div class="row">
                                <a href="{% url 'MatMan:list_metalferrous'%}" class="btn btn-warning btn-lg btn-block" role="button" aria-disabled="true">View</a>
                                <a href="#" class="btn btn-info btn-lg btn-block" role="button" aria-disabled="true">Info</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card  mx-3 my-3" style="width: 12rem;">
                    <img class="card-img-top" src="{% static 'MatMan/images/NonFerrous_Ico.png' %}" alt="Card image cap">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">Non Ferrous</h5>
                        <p class="card-text">Aluminium<br>Brass<br>Bronze<br>Copper<br>Magnesium<br>Titanium</p>
                        <div class="container-fluid" style="margin-top: auto;">
                            <div class="row">
                                <a href="{% url 'MatMan:list_metalnonferrous'%}" class="btn btn-warning btn-lg btn-block " role="button" aria-disabled="true">View</a>
                                <a href="#" class="btn btn-info btn-lg btn-block" role="button" aria-disabled="true">Info</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock Cards %}

MatMan/templates/MatMan/list_buttons.html
<a href="{% url 'MatMan:engineeringmaterial_detailview' object.id%}" class="btn btn-info btn-sm " role="button" aria-pressed="true">Details</a>
<button type="button" class="btn btn-primary btn-sm js-boltmaterial-update " data-url=#> Usage </button>
<a href=# class="btn btn-danger btn-sm " role="button" aria-pressed="true">Delete</a>

MatMan/templates/MatMan/list_ceramic.html
{% extends 'MatMan/base.html' %}
{% block Cards %}
<div class="container-fluid parts-container">
    <div class="row">
        <div class="col-md-12">
            <div class="row-no-gutters">
                {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <div class="table-responsive w-100 d-block d-md-table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID:</th>
                                <th>Name:</th>
                                <th>Owner:</th>
                                <th>Creation date:</th>
                                <th>Last changed:</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if objects %}
                            {% for object in objects %}
                            <tr>
                                <td>{{ object.id }}</td>
                                <td>{{ object.name }}</td>
                                <td>{{ object.owner }}</td>
                                <td>{{ object.created_at }}</td>
                                <td>{{ object.updated_at }}</td>
                                <td>
                                    {% include 'MatMan/list_buttons.html' %}
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}

                            <tr>
                                <th>Table is empty</th>
                            </tr>
                            {% endif %}


                        </tbody>
                    </table>
                </div>
            </div>

        </div>





    </div>
</div>

{% endblock Cards%}                   